import type {
  Candidate,
  Job,
  Activity,
  AnalyticsData,
  FunnelData,
  SkillDemand,
  DepartmentHiring,
} from "./types";

export const CANDIDATES: Candidate[] = [
  {
    id: "c1",
    name: "Aisha Patel",
    email: "aisha.patel@email.com",
    phone: "+1 (555) 234-5678",
    role: "Senior Frontend Engineer",
    department: "Engineering",
    experience: 5,
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Tailwind CSS", "Node.js"],
    education: "B.Tech Computer Science",
    university: "IIT Bombay",
    stage: "Interview",
    atsScore: 92,
    matchScore: 89,
    appliedDate: "2024-05-10",
    location: "San Francisco, CA",
    avatar: "AP",
    linkedin: "https://linkedin.com/in/aisha-patel",
    github: "https://github.com/aishapatel",
    summary:
      "Frontend-focused engineer with strong React and TypeScript expertise. Excellent project portfolio with experience in high-scale production systems. Strong understanding of performance optimization and design systems.",
    salary: "$140,000 - $160,000",
    source: "LinkedIn",
    notes: "Excellent communication skills. Strong portfolio.",
    tags: ["Top Pick", "Fast Learner"],
  },
  {
    id: "c2",
    name: "Marcus Johnson",
    email: "marcus.j@email.com",
    phone: "+1 (555) 345-6789",
    role: "Full Stack Engineer",
    department: "Engineering",
    experience: 7,
    skills: ["Python", "Django", "React", "PostgreSQL", "Docker", "AWS", "Redis"],
    education: "M.S. Software Engineering",
    university: "Stanford University",
    stage: "Shortlisted",
    atsScore: 88,
    matchScore: 85,
    appliedDate: "2024-05-08",
    location: "New York, NY",
    avatar: "MJ",
    github: "https://github.com/marcusj",
    summary:
      "Full-stack engineer with 7 years experience. Backend specialist with strong DevOps knowledge. Has led teams of 5+ engineers and shipped critical infrastructure.",
    salary: "$150,000 - $175,000",
    source: "Referral",
    notes: "Strong backend skills. Led multiple infrastructure projects.",
    tags: ["Leadership", "DevOps"],
  },
  {
    id: "c3",
    name: "Sofia Rodriguez",
    email: "sofia.r@email.com",
    phone: "+1 (555) 456-7890",
    role: "Product Designer",
    department: "Design",
    experience: 4,
    skills: ["Figma", "Framer", "Design Systems", "Prototyping", "User Research", "Sketch"],
    education: "B.Design",
    university: "RISD",
    stage: "Applied",
    atsScore: 78,
    matchScore: 82,
    appliedDate: "2024-05-15",
    location: "Austin, TX",
    avatar: "SR",
    linkedin: "https://linkedin.com/in/sofia-r",
    summary:
      "Creative designer with strong UX sensibility. Built design systems for 3 Series B startups. Expert in user research and accessibility.",
    salary: "$110,000 - $130,000",
    source: "Portfolio",
    notes: "Beautiful portfolio. Strong design system background.",
    tags: ["Creative", "UX Expert"],
  },
  {
    id: "c4",
    name: "David Kim",
    email: "david.kim@email.com",
    phone: "+1 (555) 567-8901",
    role: "Data Scientist",
    department: "Data",
    experience: 6,
    skills: ["Python", "TensorFlow", "PyTorch", "SQL", "Spark", "Kubernetes", "MLflow"],
    education: "Ph.D. Machine Learning",
    university: "MIT",
    stage: "Hired",
    atsScore: 96,
    matchScore: 94,
    appliedDate: "2024-04-20",
    location: "Boston, MA",
    avatar: "DK",
    github: "https://github.com/davidkim-ml",
    summary:
      "ML engineer with PhD from MIT. Published 4 research papers on NLP. Built production ML pipelines handling 10M+ predictions/day.",
    salary: "$175,000 - $200,000",
    source: "Direct Apply",
    notes: "Exceptional ML background. Multiple publications.",
    tags: ["PhD", "Published Researcher"],
  },
  {
    id: "c5",
    name: "Emma Wilson",
    email: "emma.wilson@email.com",
    phone: "+1 (555) 678-9012",
    role: "Backend Engineer",
    department: "Engineering",
    experience: 3,
    skills: ["Go", "gRPC", "PostgreSQL", "Redis", "Docker", "Kubernetes"],
    education: "B.S. Computer Science",
    university: "UC Berkeley",
    stage: "Screening",
    atsScore: 74,
    matchScore: 71,
    appliedDate: "2024-05-12",
    location: "Seattle, WA",
    avatar: "EW",
    github: "https://github.com/emmaw",
    summary:
      "Backend engineer specializing in distributed systems and Go. Contributed to open-source Kubernetes projects. Strong problem-solving skills.",
    salary: "$120,000 - $145,000",
    source: "GitHub",
    notes: "Strong Go skills. Active open-source contributor.",
    tags: ["Open Source", "Distributed Systems"],
  },
  {
    id: "c6",
    name: "James Thompson",
    email: "james.t@email.com",
    phone: "+1 (555) 789-0123",
    role: "DevOps Engineer",
    department: "Infrastructure",
    experience: 8,
    skills: ["AWS", "Terraform", "Ansible", "Docker", "Kubernetes", "CI/CD", "Python"],
    education: "B.S. Information Systems",
    university: "Georgia Tech",
    stage: "Rejected",
    atsScore: 65,
    matchScore: 60,
    appliedDate: "2024-05-01",
    location: "Chicago, IL",
    avatar: "JT",
    summary:
      "DevOps engineer with 8 years experience. Deep AWS expertise. Managed infrastructure for Fortune 500 companies.",
    salary: "$130,000 - $155,000",
    source: "Indeed",
    notes: "Good background but skills mismatch for current opening.",
    tags: ["AWS Expert"],
  },
  {
    id: "c7",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "+1 (555) 890-1234",
    role: "Product Manager",
    department: "Product",
    experience: 5,
    skills: ["Roadmapping", "Agile", "SQL", "Figma", "JIRA", "Analytics", "A/B Testing"],
    education: "MBA",
    university: "Wharton",
    stage: "Interview",
    atsScore: 87,
    matchScore: 86,
    appliedDate: "2024-05-07",
    location: "San Francisco, CA",
    avatar: "PS",
    linkedin: "https://linkedin.com/in/priya-sharma-pm",
    summary:
      "Product manager with MBA from Wharton. Led 3x revenue growth at previous startup. Data-driven with strong stakeholder management.",
    salary: "$155,000 - $180,000",
    source: "LinkedIn",
    notes: "Impressive product track record. Strong data skills.",
    tags: ["MBA", "Growth Expert"],
  },
  {
    id: "c8",
    name: "Alex Chen",
    email: "alex.chen@email.com",
    phone: "+1 (555) 901-2345",
    role: "Machine Learning Engineer",
    department: "AI",
    experience: 4,
    skills: ["Python", "PyTorch", "LangChain", "FastAPI", "RAG", "Vector DBs", "AWS"],
    education: "M.S. AI",
    university: "Carnegie Mellon",
    stage: "Shortlisted",
    atsScore: 91,
    matchScore: 90,
    appliedDate: "2024-05-11",
    location: "Pittsburgh, PA",
    avatar: "AC",
    github: "https://github.com/alexchen-ai",
    summary:
      "ML engineer focused on LLMs and production AI systems. Built RAG pipelines serving 100K+ users. Deep experience with modern AI stack.",
    salary: "$160,000 - $185,000",
    source: "Referral",
    notes: "Excellent LLM expertise. Strong production experience.",
    tags: ["LLM Expert", "Hot Candidate"],
  },
];

export const JOBS: Job[] = [
  {
    id: "j1",
    title: "Senior Frontend Engineer",
    department: "Engineering",
    location: "San Francisco, CA (Hybrid)",
    type: "Full-time",
    applicants: 48,
    posted: "2024-05-01",
    status: "Active",
    salary: "$140K - $160K",
    requiredSkills: ["React", "TypeScript", "Next.js", "GraphQL"],
  },
  {
    id: "j2",
    title: "Data Scientist",
    department: "Data",
    location: "Remote",
    type: "Full-time",
    applicants: 62,
    posted: "2024-04-25",
    status: "Active",
    salary: "$160K - $200K",
    requiredSkills: ["Python", "TensorFlow", "SQL", "Statistics"],
  },
  {
    id: "j3",
    title: "Product Manager",
    department: "Product",
    location: "New York, NY",
    type: "Full-time",
    applicants: 35,
    posted: "2024-05-05",
    status: "Active",
    salary: "$130K - $170K",
    requiredSkills: ["Roadmapping", "Agile", "SQL", "Analytics"],
  },
  {
    id: "j4",
    title: "ML Engineer",
    department: "AI",
    location: "Remote",
    type: "Full-time",
    applicants: 29,
    posted: "2024-05-10",
    status: "Active",
    salary: "$150K - $190K",
    requiredSkills: ["Python", "PyTorch", "LLMs", "MLOps"],
  },
  {
    id: "j5",
    title: "DevOps Engineer",
    department: "Infrastructure",
    location: "Austin, TX",
    type: "Full-time",
    applicants: 22,
    posted: "2024-04-15",
    status: "Paused",
    salary: "$120K - $150K",
    requiredSkills: ["AWS", "Kubernetes", "Terraform", "CI/CD"],
  },
];

export const ACTIVITIES: Activity[] = [
  {
    id: "a1",
    type: "interview",
    candidateName: "Aisha Patel",
    action: "Interview scheduled for Senior Frontend Engineer role",
    time: "2 minutes ago",
    avatar: "AP",
  },
  {
    id: "a2",
    type: "application",
    candidateName: "Sofia Rodriguez",
    action: "Applied for Product Designer position",
    time: "18 minutes ago",
    avatar: "SR",
  },
  {
    id: "a3",
    type: "hired",
    candidateName: "David Kim",
    action: "Offer accepted — joining as Data Scientist",
    time: "1 hour ago",
    avatar: "DK",
  },
  {
    id: "a4",
    type: "stage",
    candidateName: "Alex Chen",
    action: "Moved to Shortlisted stage for ML Engineer role",
    time: "3 hours ago",
    avatar: "AC",
  },
  {
    id: "a5",
    type: "note",
    candidateName: "Priya Sharma",
    action: "Recruiter note added — exceptional fit for PM role",
    time: "5 hours ago",
    avatar: "PS",
  },
  {
    id: "a6",
    type: "rejected",
    candidateName: "James Thompson",
    action: "Application declined — skills mismatch",
    time: "Yesterday",
    avatar: "JT",
  },
  {
    id: "a7",
    type: "application",
    candidateName: "Emma Wilson",
    action: "Resume screening completed — Score: 74",
    time: "Yesterday",
    avatar: "EW",
  },
];

export const ANALYTICS_DATA: AnalyticsData[] = [
  { month: "Jan", applications: 120, interviews: 38, hired: 8, rejected: 72 },
  { month: "Feb", applications: 145, interviews: 52, hired: 12, rejected: 81 },
  { month: "Mar", applications: 178, interviews: 61, hired: 15, rejected: 92 },
  { month: "Apr", applications: 162, interviews: 58, hired: 11, rejected: 87 },
  { month: "May", applications: 210, interviews: 75, hired: 18, rejected: 105 },
  { month: "Jun", applications: 195, interviews: 70, hired: 14, rejected: 98 },
  { month: "Jul", applications: 230, interviews: 84, hired: 22, rejected: 110 },
  { month: "Aug", applications: 248, interviews: 91, hired: 25, rejected: 118 },
];

export const FUNNEL_DATA: FunnelData[] = [
  { stage: "Applied", count: 248, percentage: 100, color: "#3B82F6" },
  { stage: "Screening", count: 186, percentage: 75, color: "#8B5CF6" },
  { stage: "Shortlisted", count: 124, percentage: 50, color: "#F59E0B" },
  { stage: "Interview", count: 74, percentage: 30, color: "#F97316" },
  { stage: "Hired", count: 25, percentage: 10, color: "#10B981" },
];

export const SKILL_DEMAND: SkillDemand[] = [
  { skill: "React", demand: 92, supply: 68 },
  { skill: "TypeScript", demand: 88, supply: 62 },
  { skill: "Python", demand: 85, supply: 74 },
  { skill: "AWS", demand: 80, supply: 55 },
  { skill: "Docker", demand: 75, supply: 60 },
  { skill: "GraphQL", demand: 70, supply: 45 },
  { skill: "Kubernetes", demand: 68, supply: 40 },
  { skill: "Go", demand: 65, supply: 38 },
];

export const DEPARTMENT_HIRING: DepartmentHiring[] = [
  { department: "Engineering", open: 12, hired: 8, target: 15 },
  { department: "Product", open: 4, hired: 2, target: 5 },
  { department: "Design", open: 3, hired: 1, target: 4 },
  { department: "Data / AI", open: 6, hired: 4, target: 8 },
  { department: "Marketing", open: 5, hired: 3, target: 6 },
  { department: "Sales", open: 8, hired: 5, target: 10 },
];

export const SOURCE_DATA = [
  { name: "LinkedIn", value: 38, color: "#0A66C2" },
  { name: "Referral", value: 22, color: "#C6A75E" },
  { name: "Direct Apply", value: 18, color: "#8B5CF6" },
  { name: "Indeed", value: 12, color: "#2164F3" },
  { name: "GitHub", value: 6, color: "#1F2A44" },
  { name: "Other", value: 4, color: "#64748B" },
];

export const STATS = {
  totalApplicants: 1248,
  activeJobs: 18,
  interviewsScheduled: 42,
  hired: 87,
  rejected: 362,
  avgTimeToHire: 18,
  offerAcceptRate: 82,
};
